const lang = {
    current: {},
    it : {
        GOOD_MORNING: "Buongiorno",
        GOOD_AFTERNOON: "Buon pomeriggio",
        GOOD_EVENING: "Buonasera",
        GOOD_NIGHT: "Buonanotte",
        HOME: "Home",
        SEARCH: "Cerca",
        LIBRARY: "Libreria",
        SETTINGS: "Impostazioni",
        GENERAL_SETTINGS: "Generali",
        ADV_SETTINGS: "Avanzate",
        ADV_SETTINGS_DISCLAIMER: "Attenzione: Queste sono impostazioni avanzate. Non modificarle se non sai cosa stai facendo!",
        SETTINGS_SAVE: "Applica",
        CAW_INST_URL: "URL del Proxy",
        CAW_DESC: "Affinch&egrave; Venom funzioni correttamente, &egrave; necessario un proxy in esecuzione su un server. Puoi lasciare quello predefinito, oppure utilizzare la tua istanza per ottenere maggiori prestazioni.",
        LANGUAGE: "Lingua",
        ITALIAN: "Italiano",
        ENGLISH: "Inglese",
        SPANISH: "Spagnolo",
        NO_NETWORK: "Nessuna connessione ad Internet",
        TRYING_CAW_CONN: "Provo la connessione al proxy",
        CAW_CONN_SUCCESS: "Connessione riuscita",
        CAW_CONN_FAILED: "Connessione fallita",
        SETTINGS_RESET: "Ripristina",
        CACHE_CLEAR: "Aggiorna",
        YTMUSIC_CONN_SUCCESS: "Connessione al server stabilita correttamente",
        YTMUSIC_CONN_ERROR: "Errore durante la connessione al server",
        SEARCH_BOX_PLACEHOLDER: "Cerca brani...",
        TRYING_YTMUSIC_CONN: "Tento connessione al server",
        RECENT_SEARCHES: "Recenti",
        SEARCH_RESULTS: "Risultati",
        DOWNLOAD_MP3: "Scarica MP3",
        ADD_TO_FAV: "Mi piace",
        CLOSE: "Chiudi",
        LOADING: "Caricamento in corso...",
        SEARCHING: "Ricerca in corso...",
        MP3_DOWNLOADING: "Download MP3",
        RETRIEVING_SONG_INFO: "Recupero metadati canzone...",
        RETRIEVING_SONG_LYRICS: "Recupero testo canzone...",
        RETRIEVING_THUMBNAIL: "Download copertina...",
        RETRIEVING_AUDIOURL: "Recupero URL Audio...",
        RETRIEVING_AUDIO: "Scarico audio...",
        AUDIO_QUALITY: "Qualit&agrave; audio",
        AUDIO_QUALITY_MAX: "Molto Alta",
        AUDIO_QUALITY_HIGH: "Alta",
        AUDIO_QUALITY_NORMAL: "Normale",
        AUDIO_QUALITY_MEDIUM: "Media",
        AUDIO_QUALITY_LOW: "Bassa",
        HIDE: "Nascondi",
        VERSION: "Versione",
        UPDATE_AVAIABLE: "Nuova versione disponibile! <a onclick='cacheclear();' id='updatebtn'>Aggiorna</a>",
        PROCESSING: "Elaboro...",
        DELETE_ALL: "CANCELLA TUTTO",
        SONGS: "Canzoni",
        VIDEOS: "Video",
        ALBUM: "Album",
        ARTISTS: "Artisti",
        ARTIST: "Artista",
        ALL: "Tutto",
        LOADING_AUDIO: "Carico Audio...",
        LIKED_SONGS_PL: "Brani che ti piacciono",
        STREAM_SVC_D: "Servizio streaming audio",
        PEER_CONN_ERROR: "ERRORE CONN.",
        SESSION_ID: "ID Sessione:",
        INSERT_SESS_ID_TRANSFER: "Inserire ID Sessione del dispositivo a cui trasferire Impostazioni e Playlist.",
        EXPORT_ALL: "Esp. Tutto",
        SAVED_SONGS_PL: "Brani Salvati",
        DOWNLOAD_SONG: "Scarica Canzone",
        REMOVE_DOWNLOAD_SONG: "Rimuovi dai download",
        DELETED: " rimosso.",
        DOWNLOADING_SONG: "Download in corso...",
        DOWNLOADED: " scaricato.",
        SHUFFLE: "RIPRODUZIONE CASUALE",
        NOW_PLAYING: "IN RIPRODUZIONE",
        LYRICS: "Testo",
        QUEUE_ADD: "Aggiungi alla coda",
    },
    en: {
        GOOD_MORNING: "Good Morning",
        GOOD_AFTERNOON: "Good Afternoon",
        GOOD_EVENING: "Good Evening",
        GOOD_NIGHT: "Goodnight",
        HOME: "Home",
        SEARCH: "Search",
        LIBRARY: "Library",
        SETTINGS: "Settings",
        GENERAL_SETTINGS: "General Settings",
        ADV_SETTINGS: "Advanced Settings",
        ADV_SETTINGS_DISCLAIMER: "These are advanced settings. If you don't know what they mean, do not touch them!",
        SETTINGS_SAVE: "Save settings",
        CAW_INST_URL: "Proxy URL",
        CAW_DESC: "Venom requires a proxy to work properly. You can host your own instance to improve speed, or you can leave everythings as it is.",
        LANGUAGE: "Language",
        ITALIAN: "Italian",
        ENGLISH: "English",
        SPANISH: "Spanish",
        NO_NETWORK: "No Internet Connection",
        TRYING_CAW_CONN: "Trying to connect to proxy",
        CAW_CONN_SUCCESS: "Success",
        CAW_CONN_FAILED: "Connection Failure",
        SETTINGS_RESET: "Reset",
        CACHE_CLEAR: "Update Venom",
        YTMUSIC_CONN_SUCCESS: "Connected to Server",
        YTMUSIC_CONN_ERROR: "Cannot connect to Server",
        SEARCH_BOX_PLACEHOLDER: "Search songs here...",
        TRYING_YTMUSIC_CONN: "Trying to connect to Server",
        RECENT_SEARCHES: "Recent Searches",
        SEARCH_RESULTS: "Results",
        DOWNLOAD_MP3: "Download as MP3",
        ADD_TO_FAV: "Add to favourites",
        CLOSE: "Close",
        LOADING: "Loading...",
        SEARCHING: "Searching...",
        MP3_DOWNLOADING: "Download MP3",
        RETRIEVING_SONG_INFO: "Retrieving song info...",
        RETRIEVING_SONG_LYRICS: "Retrieving song lyrics...",
        RETRIEVING_THUMBNAIL: "Downloading album cover...",
        RETRIEVING_AUDIOURL: "Retrieving Audio URL...",
        RETRIEVING_AUDIO: "Downloading audio...",
        AUDIO_QUALITY: "Audio Quality",
        AUDIO_QUALITY_MAX: "Very High",
        AUDIO_QUALITY_HIGH: "High",
        AUDIO_QUALITY_NORMAL: "Normal",
        AUDIO_QUALITY_MEDIUM: "Medium",
        AUDIO_QUALITY_LOW: "Low",
        HIDE: "Hide",
        VERSION: "Version",
        UPDATE_AVAIABLE: "New version avaiable! <a onclick='cacheclear();' id='updatebtn'>Update</a>",
        PROCESSING: "Processing...",
        DELETE_ALL: "DELETE ALL",
        SONGS: "Songs",
        VIDEOS: "Videos",
        ALBUM: "Album",
        ARTISTS: "Artists",
        ARTIST: "Artist",
        ALL: "All",
        LOADING_AUDIO: "Loading audio...",
        LIKED_SONGS_PL: "Songs you like",
        STREAM_SVC_D: "Current streaming service",
        PEER_CONN_ERROR: "ERROR",
        SESSION_ID: "Session ID:",
        INSERT_SESS_ID_TRANSFER: "Insert target device Session ID to transfer settings and playlists.",
        EXPORT_ALL: "Exp. All",
        SAVED_SONGS_PL: "Downloaded Songs",
        DOWNLOAD_SONG: "Download Song",
        REMOVE_DOWNLOAD_SONG: "Delete from Downloads",
        DELETED: " deleted.",
        DOWNLOADING_SONG: "Downloading song...",
        DOWNLOADED: " downloaded.",
        ONLINE_DL_DISCL: "To access the downloaded songs, you must be offline.",
        SHUFFLE: "SHUFFLE PLAY",
        NOW_PLAYING: "NOW PLAYING",
        LYRICS: "Lyrics",
        QUEUE_ADD: "Add to Queue",
    }
}